version: '3.1'

networks:
  overlay:

services:
  prometheus:
      restart: always
      image: prom/prometheus:latest
      volumes:
        - ./prometheus/:/etc/prometheus/
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention=200h'
      networks:
        - overlay

  exporter_waqi:
      restart: always
      image: exporter_external
      environment:
        - AQICN_TOKEN=<TOKEN>
        - CITIES=<cities>
      networks:
        - overlay
